-- MySQL Script generated by MySQL Workbench
-- Sat May 30 19:04:35 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema izvlacenje
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `izvlacenje` ;

-- -----------------------------------------------------
-- Schema izvlacenje
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `izvlacenje` DEFAULT CHARACTER SET utf8 ;
USE `izvlacenje` ;

-- -----------------------------------------------------
-- Table `izvlacenje`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `izvlacenje`.`admin` ;

CREATE TABLE IF NOT EXISTS `izvlacenje`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(225) NOT NULL,
  `password` VARCHAR(225) NOT NULL,
  `created_at` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `izvlacenje`.`competitor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `izvlacenje`.`competitor` ;

CREATE TABLE IF NOT EXISTS `izvlacenje`.`competitor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(225) NOT NULL,
  `email` VARCHAR(225) NOT NULL,
  `created_at` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Insert admin data
-- -----------------------------------------------------
INSERT INTO admin(`id`,`email`,`password`,`created_at`)
VALUES('1','admin@gmail.com','$2y$12$cWrOnW6KeH682o22zmxuh.yBpRwF48QiHNjv33QLvd.whjTZFOr5S',DATE(20200505));

-- -----------------------------------------------------
-- Insert competitor data
-- -----------------------------------------------------
INSERT INTO competitor(`id`,`username`,`email`,`created_at`) 
VALUES (1,'Aleksa Ivanisevic','aleksa@gmail.com',DATE(20200530)),
	(2,'Katarina Ivanisevic','kaja@gmail.com',DATE(20200531)),
	(3,'Milos Savic','miskec@gmail.com',DATE(20200525)),
	(4,'Petar Ivanisevic','petar@gmail.com',DATE(20200529)),
	(5,'Luka Cendic','cenda@gmail.com',DATE(20200531)),
	(6,'Dusan Pavlovic','dule@gmail.com',DATE(20200530)),
	(7,'Aleksa Ivanisevic','aleksa99@gmail.com',DATE(20200521)),
	(8,'Sasa Katanic','sasa.katanic61@gmail.com.rs',DATE(20200531)),
	(9,'Ankica Vucic','ankica@gmail.com',DATE(20200525)),
	(10,'Aleksa Test','aleksaivanisevictest@gmail.com',DATE(20200526)),
	(11,'Petar Petrovic','petarpetrovic@gmail.com',DATE(20200530)),
	(12,'David Ivanovic','davidivanovic02@yahho.com',DATE(20200530)),
	(13,'Nikola Lazarevic','nikolalaz1999@gmail.com',DATE(20200525));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
